### ISSUE TITLE
Flaky test when running all examples in chunks

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#531]
<img width="573" alt="Screen Shot 2020-07-16 at 3 00 41 PM" src="https://user-images.githubusercontent.com/2212006/87711365-2ab7a180-c775-11ea-856e-a5015486d88b.png">

We need to record tests that run with 

```
  # a single utility job that can run multiple examples one by one
  # but with chunking
  test-examples:
    parallelism: 20
    working_directory: ~/app
    docker:
      - image: cypress/base:10
    environment:
      TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      # when running in parallel, the total number of parallel containers
      # is in variable CIRCLE_NODE_TOTAL and the current container index in CIRCLE_NODE_INDEX
      # which starts at 0 and goes to $CIRCLE_NODE_TOTAL - 1
      - run: npm run test:ci -- --chunk $CIRCLE_NODE_INDEX --total-chunks $CIRCLE_NODE_TOTAL
```
